using Project.Models;
using Project.Models.Status;
using static System.Net.Mime.MediaTypeNames;

User Assignee=new User("sari","123@",Project.Enum.Role.manager, ConsoleNotify.Instance);
User user = new User("racheli", "123@", Project.Enum.Role.developer, ConsoleNotify.Instance);
var TaskBuilder2 = new TaskBuilder("java program");
TaskBuilder2.BuildDescription("costumer");
TaskBuilder2.BuildLoggedTime();
TaskBuilder2.BuildPriority(Project.Enum.Priority.High);
TaskBuilder2.BuildEstimationTime(1.5f);
TaskBuilder2.BuildAssignee(user);
TaskBuilder2.BuildReporter(user);
var Task2 = TaskBuilder2.build();
Task2.TaskState = (new ToDoState(Task2));

var TaskBuilder = new TaskBuilder("java program");
TaskBuilder.BuildDescription("pizza shop");
TaskBuilder.BuildLoggedTime();
TaskBuilder.BuildPriority(Project.Enum.Priority.Low);
TaskBuilder.BuildEstimationTime(2f);
TaskBuilder.BuildAssignee(Assignee);
TaskBuilder.BuildReporter(user);
TaskBuilder.BuildSubTasks(Task2);
var Task3 = TaskBuilder.build();
Task3.TaskState = (new ToDoState(Task3));


var TaskBuilder3 = new TaskBuilder("java program");
TaskBuilder3.BuildDescription("pizza shop");
TaskBuilder3.BuildLoggedTime();
TaskBuilder3.BuildPriority(Project.Enum.Priority.Low);
TaskBuilder3.BuildEstimationTime(14.5f);
TaskBuilder3.BuildAssignee(Assignee);
TaskBuilder3.BuildReporter(Assignee);
TaskBuilder3.BuildSubTasks(Task3);
var Task1 = TaskBuilder3.build();
Task1.TaskState =( new ToDoState(Task1));


Console.WriteLine("before change");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Title= "c# project";
Console.WriteLine("after change");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.EstimationTime= 10;
Console.WriteLine("after change");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Next();
Console.WriteLine("after change");
Task1.Next();
Console.WriteLine("after change");
Task1.Undo();
Console.WriteLine("undo");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Undo();
Console.WriteLine("undo");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Undo();
Console.WriteLine("undo");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Undo();
Console.WriteLine("undo");
Console.WriteLine(Task1.Title);
Console.WriteLine(Task1.EstimationTime);
Task1.Next();
Task1.Next();
Task1.Next();
Task3.LoggedTime = 2;
Task2.LoggedTime = 2;
Task1.LoggedTime = 4;
Console.WriteLine("the logged time is");
Console.WriteLine(Task1.UpdateLoggedtime()); 